spring.application.name=platform

spring.datasource.url=jdbc:postgresql://localhost:5432/ss-platform
spring.datasource.username=ssant0
spring.datasource.password=2004
spring.datasource.driver-class-name=org.postgresql.Driver

security.jwt.secret=cucii-platform-super-secret-key-change-in-production-2024
security.jwt.expiration=86400000

