
services:
  db:
    container_name: cucii-ss-platform
    image: postgres:18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=2004
      - POSTGRES_USER=ssant0
      - POSTGRES_DB=ss-platform
    volumes:
      - ss-platform-data:/var/lib/postgresql
      - ./db_structure.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  ss-platform-data: